# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba6451a2b4ecfee20ac08d9a2ba0a5aec3f7dcc3514f4b1ca695c21471ef1804bfc18847ba0472c32e5708f7b93846bc40a119f3174e3e4641320a2e19da15b

test:
  secret_key_base: 43a71a136a406e9d8008dc539136ccf5c6dbf7cb9b4ebcaa7cfe788527a91ee5c152ba202ff3172ec6db74be18f632fe8b3aca6f0559f898e3d9a1a7a7f1e36f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
